services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    build: .
    environment:
      - PORT=5000
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
  mongo:
    image: mongo
    env_file:
      - mongo.env
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
